[package]
name = "optifree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
assert_unordered = "0.3.5"
geo = "0.25.0"
ordered-float = "3.7.0"
rand = "0.8.5"
uom = "0.34.0"
